import { ProductType } from "@/app/types/product";
import {
  HoodiesCollection,
  Shorts,
  Snapback,
  Jacket,
} from "@/public/our products";

import {
  blackHoodie,
  greenHoodie,
  brownHoodie,
  hazeBlueHoodie,
  darkGrayHoodie,
  lightGrayHoodie,
  sandHoodie,
} from "@/public/productDetails/hoodies";
import {
  blueTshirt,
  blackTshirt,
  coffeeTshirt,
  dirtyWhiteTshirt,
  grayTshirt,
  brownTshirt,
  cementGrayTshirt,
} from "@/public/productDetails/t-shirts";

import {
  whiteLaSnapback,
  whiteSnapback,
  blueLaSnapback,
} from "@/public/productDetails/caps";

import {
  blackJacket,
  brownJacket,
  whiteJacket,
} from "@/public/productDetails/jacket";

import {
  blackDoubleKneeWorkPants,
  greenDoubleKneeWorkPants,
  apricotDoubleKneeWorkPants,
  khakiDoubleKneeWorkPants,
} from "@/public/productDetails/double-knee-work-pants";
import {
  blackShort,
  grayShort,
  greenShort,
} from "@/public/productDetails/shorts";
import {
  blackLooseHoodie,
  brownLooseHoodie,
  grayLooseHoodie,
  whiteLooseHoodie,
} from "@/public/productDetails/loose-hoodies";
import {
  beigeLongSleeveTshirts,
  blackLongSleeveTshirts,
  browLongSleeveTshirts,
  geayLongSleeveTshirts,
  whiteLongSleeveTshirts,
  greenLongSleeveTshirts,
} from "@/public/productDetails/long-sleeve-t-shirts";
import {
  ashColarValez,
  blackColarValez,
  brownColarValez,
  grayColarValez,
  whiteColarValez,
} from "@/public/productDetails/colar-valez-sweater";

import {
  HoodyHeavenly,
  TshirtHeavenly,
  CapHeavenly,
} from "@/public/productSeller";

export const DEFAULT_SIZE_OPTIONS = [
  { name: "S", symbol: "S", fullName: "Small" },
  { name: "M", symbol: "M", fullName: "Medium" },
  { name: "L", symbol: "L", fullName: "Large" },
  { name: "XL", symbol: "XL", fullName: "Extra Large" },
];

export const DEFAULT_SIZE_CHART = [
  {
    size: "S",
    chest: '38-40"',
    length: '27"',
    name: "S",
    symbol: "S",
    fullName: "Small",
  },
  {
    size: "M",
    chest: '41-43"',
    length: '28"',
    name: "M",
    symbol: "M",
    fullName: "Medium",
  },
  {
    size: "L",
    chest: '44-46"',
    length: '29"',
    name: "L",
    symbol: "L",
    fullName: "Large",
  },
  {
    size: "XL",
    chest: '47-49"',
    length: '30"',
    name: "XL",
    symbol: "XL",
    fullName: "Extra Large",
  },
];

export const PANTS_SIZE_CHART = [
  { size: "30", chest: "-", length: '39"' },
  { size: "32", chest: "-", length: '40"' },
  { size: "34", chest: "-", length: '41"' },
  { size: "36", chest: "-", length: '42"' },
];

export const SNAPBACK_SIZE_CHART = null; // one-size

const defaultMeta = {
  longDescription:
    "A premium cotton garment designed for everyday comfort and style. Made with high-quality materials and tailored for a relaxed fit, this piece will quickly become a wardrobe essential.",
  shortDescription:
    "Soft, breathable, and sustainably made — your new favorite everyday item.",
  highlights: [
    "100% organic cotton",
    "Relaxed fit",
    "Pre-shrunk & garment dyed",
    "Machine washable",
    "Made in Portugal",
  ],
  shippingReturns:
    "Free standard shipping on orders over $50. We also offer expedited shipping at checkout. To return an item, please visit our returns portal and use your order number to start the process.",
  sizeFit:
    "Fits true to size. For a looser fit, consider sizing up. Fabric has slight stretch.",
  sizeChart: DEFAULT_SIZE_CHART,
  sizeOptions: DEFAULT_SIZE_OPTIONS,
};

const defaultProductMeta = {
  size: { name: "M", symbol: "M", fullName: "Medium" },
  color: { name: "Blue", image: HoodiesCollection },
  quantity: 1,
};

export const Products: ProductType[] = [
  {
    id: "1",
    name: "Loose Perfect Hoodie",
    image: HoodiesCollection,
    rating: 4.5,
    price: "30k FRW",
    reviews: 20,
    category: "Hoodies",
    stock: 50,
    size: defaultProductMeta.size,
    color: { name: "Dark Gray", image: darkGrayHoodie },
    quantity: defaultProductMeta.quantity,
    colorOptions: [
      { name: "Black", image: blackHoodie },
      { name: "Dark Gray", image: darkGrayHoodie },
      { name: "Haze Blue", image: hazeBlueHoodie },
      { name: "Green", image: greenHoodie },
      { name: "Brown", image: brownHoodie },
      { name: "Sand", image: sandHoodie },
      { name: "Light Gray", image: lightGrayHoodie },
    ],
    ...defaultMeta,
    isFeatured: false,
  },
  {
    id: "2",
    name: "T-shirt",
    image: blueTshirt,
    rating: 4.8,
    price: "25k FRW",
    reviews: 15,
    category: "T-shirts",
    stock: 30,
    size: defaultProductMeta.size,
    color: { name: "Blue", image: blueTshirt },
    quantity: defaultProductMeta.quantity,
    colorOptions: [
      { name: "Blue", image: blueTshirt },
      { name: "Black", image: blackTshirt },
      { name: "Coffee", image: coffeeTshirt },
      { name: "Dirty White", image: dirtyWhiteTshirt },
      { name: "Gray", image: grayTshirt },
      { name: "Brown", image: brownTshirt },
      { name: "Cement Gray", image: cementGrayTshirt },
    ],
    ...defaultMeta,
    isFeatured: false,
  },
  {
    id: "3",
    name: "Double Knee Work Pant",
    image: blackDoubleKneeWorkPants,
    rating: 4.8,
    price: "25k FRW",
    reviews: 15,
    category: "Pants",
    stock: 30,
    size: defaultProductMeta.size,
    color: { name: "Black", image: blackDoubleKneeWorkPants },
    quantity: defaultProductMeta.quantity,
    colorOptions: [
      { name: "Black", image: blackDoubleKneeWorkPants },
      { name: "Green", image: greenDoubleKneeWorkPants },
      { name: "Apricot", image: apricotDoubleKneeWorkPants },
      { name: "Khaki", image: khakiDoubleKneeWorkPants },
    ],
    ...defaultMeta,
    isFeatured: false,
  },
  {
    id: "4",
    name: "Quick Dry short",
    image: Shorts,
    rating: 4.8,
    price: "25k FRW",
    reviews: 15,
    category: "Shorts",
    stock: 30,
    size: defaultProductMeta.size,
    color: defaultProductMeta.color,
    quantity: defaultProductMeta.quantity,
    colorOptions: [
      { name: "Black", image: blackShort },
      { name: "Green", image: greenShort },
      { name: "Gray", image: grayShort },
    ],
    ...defaultMeta,
    isFeatured: false,
  },
  {
    id: "5",
    name: "Snapback",
    image: Snapback,
    rating: 4.8,
    price: "25k FRW",
    reviews: 15,
    category: "Snapback",
    stock: 30,
    size: defaultProductMeta.size,
    color: defaultProductMeta.color,
    quantity: defaultProductMeta.quantity,
    colorOptions: [
      { name: "White", image: whiteLaSnapback },
      { name: "Beige", image: whiteSnapback },
      { name: "Blue", image: blueLaSnapback },
    ],
    ...defaultMeta,
    isFeatured: false,
  },
  {
    id: "7",
    name: "Vintage Jacket",
    image: Jacket,
    rating: 4.8,
    price: "25k FRW",
    reviews: 15,
    category: "Jacket",
    stock: 30,
    size: defaultProductMeta.size,
    color: defaultProductMeta.color,
    quantity: defaultProductMeta.quantity,
    colorOptions: [
      { name: "Black", image: blackJacket },
      { name: "Brown", image: brownJacket },
      { name: "White", image: whiteJacket },
    ],
    ...defaultMeta,
    isFeatured: true,
  },
  {
    id: "8",
    name: "Rastus Loose Hoodie",
    image: blackLooseHoodie,
    rating: 4.8,
    price: "25k FRW",
    reviews: 15,
    category: "Hoodies",
    stock: 30,
    size: defaultProductMeta.size,
    color: { name: "Black", image: blackLooseHoodie },
    quantity: defaultProductMeta.quantity,
    colorOptions: [
      { name: "Black", image: blackLooseHoodie },
      { name: "Brown", image: brownLooseHoodie },
      { name: "Gray", image: grayLooseHoodie },
      { name: "White", image: whiteLooseHoodie },
    ],
    ...defaultMeta,
    isFeatured: false,
  },

  {
    id: "9",
    name: "Long Sleeve T-Shirts",
    image: whiteLongSleeveTshirts,
    rating: 4.8,
    price: "25k FRW",
    reviews: 15,
    category: "T-shirts",
    stock: 30,
    size: defaultProductMeta.size,
    color: { name: "White", image: whiteLongSleeveTshirts },
    quantity: defaultProductMeta.quantity,
    colorOptions: [
      { name: "White", image: whiteLongSleeveTshirts },
      { name: "Black", image: blackLongSleeveTshirts },
      { name: "Beige", image: beigeLongSleeveTshirts },
      { name: "Brown", image: browLongSleeveTshirts },
      { name: "Gray", image: geayLongSleeveTshirts },
      { name: "Green", image: greenLongSleeveTshirts },
    ],
    ...defaultMeta,
    isFeatured: true,
  },
  {
    id: "10",
    name: "Rastus Colar Valez",
    image: ashColarValez,
    rating: 4.7,
    price: "20k FRW",
    reviews: 15,
    category: "T-shirt",
    stock: 30,
    size: defaultProductMeta.size,
    color: defaultProductMeta.color,
    quantity: defaultProductMeta.quantity,
    colorOptions: [
      { name: "Ash", image: ashColarValez },
      { name: "Brown", image: brownColarValez },
      { name: "Black", image: blackColarValez },
      { name: "Gray", image: grayColarValez },
      { name: "White", image: whiteColarValez },
    ],
    ...defaultMeta,
    isFeatured: true,
  },
  {
    id: "11",
    name: "Be Fearlessly Hoodie",
    image: HoodyHeavenly,
    rating: 4.5,
    price: "30k FRW",
    reviews: 15,
    category: "T-shirt",
    stock: 30,
    size: defaultProductMeta.size,
    color: { name: "Red", image: HoodyHeavenly },
    quantity: 1,
    colorOptions: [{ name: "Red", image: HoodyHeavenly }],
    ...defaultMeta,
    isFeatured: true,
  },
  {
    id: "12",
    name: "Old School T-Shirt",
    image: TshirtHeavenly,
    rating: 4.7,
    price: "24k FRW",
    reviews: 15,
    category: "T-shirt",
    stock: 30,
    size: defaultProductMeta.size,
    color: { name: "Red", image: TshirtHeavenly },
    quantity: defaultProductMeta.quantity,
    colorOptions: [{ name: "Gray", image: TshirtHeavenly }],
    ...defaultMeta,
    isFeatured: true,
  },
  {
    id: "13",
    name: "Rastus White snapback",
    image: CapHeavenly,
    rating: 4.8,
    price: "15k FRW",
    reviews: 15,
    category: "T-shirt",
    stock: 30,
    size: { name: "M", symbol: "M", fullName: "Medium" },
    color: { name: "Creamy and Black", image: CapHeavenly },
    quantity: defaultProductMeta.quantity,
    colorOptions: [{ name: "Creamy and Black", image: CapHeavenly }],
    ...defaultMeta,
    isFeatured: true,
  },
];
