import { ProductType } from "@/app/types/product";
import {
  HoodiesCollection,
  LongTshirts,
  Pants,
  Shorts,
  Snapback,
  Ccap,
  Jacket,
  Jeans,
  SoftLongValez,
  TShirt,
} from "@/public/our products";

export const DEFAULT_SIZE_CHART = [
  { size: "S", chest: '38-40"', length: '27"' },
  { size: "M", chest: '41-43"', length: '28"' },
  { size: "L", chest: '44-46"', length: '29"' },
  { size: "XL", chest: '47-49"', length: '30"' },
];

export const PANTS_SIZE_CHART = [
  { size: "30", chest: "-", length: '39"' },
  { size: "32", chest: "-", length: '40"' },
  { size: "34", chest: "-", length: '41"' },
  { size: "36", chest: "-", length: '42"' },
];

export const SNAPBACK_SIZE_CHART = null; // one-size

const defaultMeta = {
  longDescription:
    "A premium cotton garment designed for everyday comfort and style. Made with high-quality materials and tailored for a relaxed fit, this piece will quickly become a wardrobe essential.",
  shortDescription:
    "Soft, breathable, and sustainably made — your new favorite everyday item.",
  highlights: [
    "100% organic cotton",
    "Relaxed fit",
    "Pre-shrunk & garment dyed",
    "Machine washable",
    "Made in Portugal",
  ],
  shippingReturns:
    "Free standard shipping on orders over $50. We also offer expedited shipping at checkout. To return an item, please visit our returns portal and use your order number to start the process.",
  sizeFit:
    "Fits true to size. For a looser fit, consider sizing up. Fabric has slight stretch.",
  sizeChart: DEFAULT_SIZE_CHART,
};

const defaultProductMeta = {
  size: { name: "M", symbol: "M", fullName: "Medium" },
  color: { name: "Blue", image: HoodiesCollection },
  quantity: 1,
};

export const Products: ProductType[] = [
  {
    id: "1",
    name: "Hoodies",
    image: HoodiesCollection,
    rating: 4.5,
    price: "30k FRW",
    reviews: 20,
    category: "Hoodies",
    stock: 50,
    size: defaultProductMeta.size,
    color: defaultProductMeta.color,
    quantity: defaultProductMeta.quantity,
    ...defaultMeta,
  },
  {
    id: "2",
    name: "Long T-shirts",
    image: LongTshirts,
    rating: 4.8,
    price: "25k FRW",
    reviews: 15,
    category: "T-shirts",
    stock: 30,
    size: defaultProductMeta.size,
    color: defaultProductMeta.color,
    quantity: defaultProductMeta.quantity,
    ...defaultMeta,
  },
  {
    id: "3",
    name: "Pants",
    image: Pants,
    rating: 4.8,
    price: "25k FRW",
    reviews: 15,
    category: "Pants",
    stock: 30,
    size: defaultProductMeta.size,
    color: defaultProductMeta.color,
    quantity: defaultProductMeta.quantity,
    ...defaultMeta,
  },
  {
    id: "4",
    name: "Shorts",
    image: Shorts,
    rating: 4.8,
    price: "25k FRW",
    reviews: 15,
    category: "Shorts",
    stock: 30,
    size: defaultProductMeta.size,
    color: defaultProductMeta.color,
    quantity: defaultProductMeta.quantity,
    ...defaultMeta,
  },
  {
    id: "5",
    name: "Snapback",
    image: Snapback,
    rating: 4.8,
    price: "25k FRW",
    reviews: 15,
    category: "Snapback",
    stock: 30,
    size: defaultProductMeta.size,
    color: defaultProductMeta.color,
    quantity: defaultProductMeta.quantity,
    ...defaultMeta,
  },
  {
    id: "6",
    name: "C-cap",
    image: Ccap,
    rating: 4.8,
    price: "25k FRW",
    reviews: 15,
    category: "C-cap",
    stock: 30,
    size: defaultProductMeta.size,
    color: defaultProductMeta.color,
    quantity: defaultProductMeta.quantity,
    ...defaultMeta,
  },
  {
    id: "7",
    name: "Jacket",
    image: Jacket,
    rating: 4.8,
    price: "25k FRW",
    reviews: 15,
    category: "Jacket",
    stock: 30,
    size: defaultProductMeta.size,
    color: defaultProductMeta.color,
    quantity: defaultProductMeta.quantity,
    ...defaultMeta,
  },
  {
    id: "8",
    name: "Jeans",
    image: Jeans,
    rating: 4.8,
    price: "25k FRW",
    reviews: 15,
    category: "Jeans",
    stock: 30,
    size: defaultProductMeta.size,
    color: defaultProductMeta.color,
    quantity: defaultProductMeta.quantity,
    ...defaultMeta,
  },

  {
    id: "9",
    name: "Soft Long Valez",
    image: SoftLongValez,
    rating: 4.8,
    price: "25k FRW",
    reviews: 15,
    category: "Soft Long Valez",
    stock: 30,
    size: defaultProductMeta.size,
    color: defaultProductMeta.color,
    quantity: defaultProductMeta.quantity,
    ...defaultMeta,
  },
  {
    id: "10",
    name: "T-shirt",
    image: TShirt,
    rating: 4.7,
    price: "20k FRW",
    reviews: 15,
    category: "T-shirt",
    stock: 30,
    size: defaultProductMeta.size,
    color: defaultProductMeta.color,
    quantity: defaultProductMeta.quantity,
    ...defaultMeta,
  },
];
